root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  full_bin = "build/go-app"
  cmd = "go build -o build/go-app main.go"
  args_bin = []
  pre_cmd = ["pkill -f go-app"]
  post_cmd = []
  exclude_dir = ["static", "assets"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = ["cmd", "pkg", "internal"]
  include_file = ["main.go"]
  include_ext = ["go", "templ"]
  kill_delay = "1s"
  delay = 500
  log = "build/build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = "blue"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
